# Generated by Django 5.2.9 on 2025-12-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barlery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('beer', 'Beer'), ('wine', 'Wine'), ('spirit', 'Spirit'), ('non-alcoholic', 'Non-Alcoholic')], default='beer', max_length=20, verbose_name='Category'),
        ),
    ]
