# Generated by Django 5.2.9 on 2025-12-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barlery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
