# Generated by Django 5.2.9 on 2025-12-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barlery', '0002_weeklyhours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyhours',
            options={'verbose_name': 'Weekly hours', 'verbose_name_plural': 'Weekly hours'},
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='friday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='friday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='monday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='monday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='saturday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='saturday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='sunday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='sunday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='thursday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='thursday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='tuesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='tuesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='wednesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyhours',
            name='wednesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
