# Generated by Django 5.2.9 on 2025-12-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barlery', '0002_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Event promotional image', null=True, upload_to='events/'),
        ),
    ]
